# Generated by Django 5.0.14 on 2026-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquizanswer',
            name='option',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentquizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentquizanswer',
            name='attempt',
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='answers_submitted',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentQuizAnswer',
        ),
    ]
