# Generated by Django 5.0.14 on 2026-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_studentquizanswer_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='questions_snapshot',
            field=models.JSONField(default=list),
        ),
    ]
